### ISSUE TITLE
interactive apt-cacher-ng dialogue blocks CI indefinitely

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#16]
There is an interactive dialogue for the package `apt-cacher-ng` that waits for a yes/no user response:
```
Setting up apt-cacher-ng (3.3.1-2build1) ...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Configuring apt-cacher-ng
-------------------------

Apt-Cacher NG can be configured to allow users to create HTTP tunnels, which
can be used to access remote servers that might otherwise be blocked by (for
instance) a firewall filtering HTTPS connections.

This feature is usually disabled for security reasons; enable it only for
trusted LAN environments.

Allow HTTP tunnels through Apt-Cacher NG? [yes/no] 
```

**Comment by jspricke** [comment]
Do you see it while running as a Github Action or locally?

**Comment by christian-rauch** [comment]
> Do you see it while running as a Github Action or locally?

As a GitHub Action.

**Comment by jspricke** [comment]
You can ignore that, it defaults to false and should work just fine.

**Comment by jspricke** [comment]
can you share a link where it blocks? At least in my tests it does not.

**Comment by christian-rauch** [comment]
> can you share a link where it blocks? At least in my tests it does not.

No, sorry. I am using this in a non-private instance. If it helps, I am using the `ros:foxy-ros-core-focal` and `ros:humble-ros-core-jammy` Docker images.

**Comment by jspricke** [comment]
Can you try this commit: e1717d1

**Comment by christian-rauch** [comment]
I am still getting this blocking on the `main` branch of the action. I assume that `DEBIAN_FRONTEND` does not affect the `apt-cacher-ng` installation.

Running
```
DEBIAN_FRONTEND=noninteractive sudo apt install apt-cacher-ng
```
locally also gives me the yes/no dialogue.

Is it possible to make `apt-cacher-ng` optional?

**Comment by jspricke** [comment]
Can you try with 09f5cd0

**Comment by christian-rauch** [comment]
I now get a different error and I don't know if this happens before or after the original `apt-cacher-ng` issue.

Now, something with the repo URL is wrong:
```
+ echo Setup build environment
+ mkdir -p /github/home/.cache/sbuild
Setup build environment
+ mmdebstrap --variant=buildd --include=apt,ccache,auto-apt-proxy --customize-hook=chroot "$1" update-ccache-symlinks --components=main,universe focal /github/home/.cache/sbuild/focal-amd64.tar
I: automatically chosen mode: root
I: chroot architecture amd64 is equal to the host's architecture
I: Reading sources.list from standard input...
I: running apt-get update...
Ign:1 http://deb.debian.org/debian focal InRelease
Err:2 http://deb.debian.org/debian focal Release
  404  Not Found [IP: 199.232.150.132 80]
Reading package lists...
E: The repository 'http://deb.debian.org/debian focal Release' does not have a Release file.
E: apt-get update -oAPT::Status-Fd=<$fd> -oDpkg::Use-Pty=false failed
```

`apt` is trying to use the Debian URL (http://deb.debian.org/debian) for the Ubuntu `focal` release.

**Comment by jspricke** [comment]
That's after the original issue. Your errors look really odd and nothing I've experienced with Github Actions till now. Can you give me some details on your setup via private mail?

**Comment by jspricke** [comment]
> I: automatically chosen mode: root

That does not sound like a Github Action run, it should be:

>I: automatically chosen mode: unshare

Sounds like user namespaces are not available on your setup which would need an entire different setup.

**Comment by jspricke** [comment]
> Running
> 
> ```
> DEBIAN_FRONTEND=noninteractive sudo apt install apt-cacher-ng
> ```
> 
> locally also gives me the yes/no dialogue.

sudo drops the environment, either run it as root or try sudo -E

**Comment by christian-rauch** [comment]
> sudo drops the environment, either run it as root or try sudo -E

Right. `DEBIAN_FRONTEND=noninteractive sudo -E apt install apt-cacher-ng` does not give me the dialogue.

**Comment by christian-rauch** [comment]
My originally reported issue was fixed by 09f5cd03eb65dd138b2553f989ba567ed89a014c but then reintroduced by the revert in eea115fd00968a08fefa0250e0b0fce35b42147a. Can we keep the change in 09f5cd03eb65dd138b2553f989ba567ed89a014c in order to not block `apt-cacher-ng`?

**Comment by jspricke** [comment]
No, it broke the GIthub Action, sorry for the revert. I really need more information on your setup to help you. Can you please provide some?

**Comment by jspricke** [comment]
I've added -E to sudo now, so it should have the same effect. Sorry for not thinking of that before.

**Comment by christian-rauch** [comment]
With the `humble` Docker image (https://github.com/jspricke/ros-deb-builder-action/issues/16#issuecomment-1451563623) I am also getting issues when packages are installed:
```
The following packages have unmet dependencies:
 python3-catkin-pkg : Conflicts: catkin but 0.8.10-7 is to be installed
 python3-catkin-pkg-modules : Conflicts: catkin but 0.8.10-7 is to be installed
 python3-rosdep : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
 python3-rosdep-modules : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.

[...]

E: Unable to locate package colcon
```
whereas the `foxy` Docker image gives me this `E: The repository 'http://deb.debian.org/debian focal Release' does not have a Release file.` error.

Can you reproduce any of my issues via the Docker containers?

> No, it broke the GIthub Action, sorry for the revert. I really need more information on your setup to help you. Can you please provide some?

I will try to create a minimal reproducible example that I can share later. For the time being, could we reopen this issue and keep it open to track this problem in case someone else is encountering this?

---

This GitHub Action is a really nice project and I like the idea of packaging a workspace and deploying the packages via a single repo. This simplifies the problem of distributing custom ROS packages a lot.

**Comment by jspricke** [comment]
Github Actions use a VM and not Docker also afaik Docker does not support user namespaces. Please run this Action without Docker when trying it locally. Sorry.
