### ISSUE TITLE
Optionally put files into github action artifact instead of pushing binaries into a branch in the repo

### ISSUE THREAD

**Issue by lucasw** [jspricke/ros-deb-builder-action#17]
It looks like this `repository` step https://github.com/jspricke/ros-deb-builder-action/blob/main/action.yaml#L60-L67 is is what does the push, a different script could be called to do a `actions/upload-artifact@v2` instead after zipping up the outputs.

Those artifacts expire after so many days, another good option to have would be to make the files into release assets on a new github release page optionally (so not on every push)- I don't know how to do that from an action though, I've always had to manually download the artifacts and then upload them into the release page.

**Comment by jspricke** [comment]
You can simply not set `$GITHUB_TOKEN` and instead add your own publish job afterwards: https://github.com/jspricke/ros-deb-builder-action/blob/main/repository#L41

I don't see a zip file as a valid output to this as it is not receivable by apt but support for uploading via ssh or alike is planned.

Closing as not planned.
