### ISSUE TITLE
Last changes makes action to fail on rosdep update?

### ISSUE THREAD

**Issue by orensbruli** [jspricke/ros-deb-builder-action#18]
Failing:
https://github.com/orensbruli/robocomp2/actions/runs/4351736150/jobs/7603694844#step:2:517

Pointing the action to 396644fa66c76ead44b3b10067681e075498548e makes it work again.

Working (not failing at that point):
https://github.com/orensbruli/robocomp2/actions/runs/4351768583/jobs/7603756863

@jspricke If I must guess I think it could be related to this:
https://github.com/jspricke/ros-deb-builder-action/commit/cbb3fe3544f9ce53e9a7d73808b1242a9252b736

But not sure.

**Comment by jspricke** [comment]
Should be fixed, sorry and thanks for the quick notice.

**Comment by orensbruli** [comment]
No problem I was just playing with it and the started to fail on a line previous to the one I was doing fixes for.
It's working great to find final dependences of my package.
