### ISSUE TITLE
Is there a way to ignore some packages from being built?

### ISSUE THREAD

**Issue by esteve** [jspricke/ros-deb-builder-action#19]
There are some packages in my `.repos` file I'd like to ignore. Adding a `COLCON_IGNORE` file between running the `prepare` and `build` scripts separately in my local machine works, but I haven't found a way to do it from the Github action, unless I replicate the action by running `prepare`, then touching the `COLCON_IGNORE` files and then `build`. Does such option exist? Or would need to be implemented?

**Comment by esteve** [comment]
As an input to the action https://github.com/jspricke/ros-deb-builder-action/blob/main/action.yaml#L7

**Comment by jspricke** [comment]
I'm not really happy with that approach as it would add `sources.repos` content to the job definition. Maybe as a principal question: do you need to skip them or is it enough to ignore a build failure?

**Comment by esteve** [comment]
Could you elaborate what you mean by `add `sources.repos` content to the job definition`? Currently there's a bunch of files in the `src` directory that are generated by the `build` script.

Alternatively, instead of creating `COLCON_IGNORE` files, the list can be checked in https://github.com/jspricke/ros-deb-builder-action/blob/main/build#L95 and exit the subshell if a package matches

**Comment by jspricke** [comment]
> Could you elaborate what you mean by `add `sources.repos` content to the job definition`? Currently there's a bunch of files in the `src` directory that are generated by the `build` script.

the list of packages to be build is defined by the `sources.repos` (by default) whereas the Action `build.yaml` defines meta information for the action. Adding them would mix layers. An acceptable solution would be to add an extra files with jobs to exclude but I hope we fine a better one.

> Alternatively, instead of creating `COLCON_IGNORE` files, the list can be checked in https://github.com/jspricke/ros-deb-builder-action/blob/main/build#L95 and exit the subshell if a package matches

Sure, the actual implementation is easy, let's keep this issue in the design phase first. (you did not answer my question, btw.).

**Comment by esteve** [comment]
> the list of packages to be build is defined by the `sources.repos` (by default) whereas the Action `build.yaml` defines meta information for the action. Adding them would mix layers. An acceptable solution would be to add an extra files with jobs to exclude but I hope we fine a better one.

I honestly don't see the problem with adding such option, we've used `action-ros-ci` which allows limiting what packages to include from a `.repos` (https://github.com/ros-tooling/action-ros-ci/blob/master/action.yml#L43) and I don't see any architectural issues with this approach.

> (you did not answer my question, btw.).

Because I don't want to turn this discussion into what we actually need/want. We do want to skip packages that we know can't be built.

**Comment by jspricke** [comment]
@esteve implemented in #22, can you have a quick look?
