### ISSUE TITLE
Do you have plan to support ubuntu 20.04 & Foxy?

### ISSUE THREAD

**Issue by jginesclavero** [jspricke/ros-deb-builder-action#20]
Hi @jspricke! Thank you for your work! IDK if you plan to support Foxy in your GithubAction, I did some tests with a custom msg package and it works well in Humble but not in Foxy.

**Comment by jspricke** [comment]
Can you share a link to your test? I would assume Foxy to work.

**Comment by jginesclavero** [comment]
Yes, of course! -- https://github.com/jginesclavero/watchbot2_deb/actions/runs/4402520324

**Comment by jspricke** [comment]
You need to change this line back to 22.04: https://github.com/jginesclavero/watchbot2_deb/blob/main/.github/workflows/build.yml

The VM system is unrelated to the system that is build for.
