### ISSUE TITLE
Bloom version seems to be quite old

### ISSUE THREAD

**Issue by russkel** [jspricke/ros-deb-builder-action#24]
Looking at the CI build log I see:
```This version of bloom is '0.10.7', but the newest available version is '0.11.2'. Please update.```

On my jammy machine it shows:
```python3-bloom/jammy,now 0.11.2-100 all [installed,auto-removable]```

It should probably be installed via pip instead of via dated ubuntu repos?

**Comment by jspricke** [comment]
Bloom runs on the host VM which is Ubuntu 22.04 that contains bloom 0.10.7. Is there a specific reason you ask for a new version?
Looking at the diff: https://github.com/ros-infrastructure/bloom/compare/0.10.7...0.11.2 I don't really see a reason (except https://github.com/ros-infrastructure/bloom/pull/661 maybe).

**Comment by russkel** [comment]
> Is there a specific reason you ask for a new version?

Not really no, just consistency with a standard install.

**Comment by jspricke** [comment]
There is always new software. The reason for having distributions like Ubuntu is to have a secure source of a known working version.

**Comment by russkel** [comment]
I made a mistake mentioning pip, my proposed solution was adding the ROS2 apt repo first before installing.

After adding ROS2 apt repo you will find `python3-bloom` and friends will want to be upgraded with the stable versions used elsewhere in the ROS2 ecosystem.

While I haven't had issues with `bloom` (as we run a patched version) I have with rosdep and its dependencies (`rospkg` etc) needing to be updated due to some breaking issue.

**Comment by jspricke** [comment]
Can you be more specific with your issue? A link to a log would be great.
