### ISSUE TITLE
Use docker images for the 'prepare' step

### ISSUE THREAD

**Issue by orensbruli** [jspricke/ros-deb-builder-action#26]
The prepare step is pretty similar for every build and I'm wondering if we could improve the action execution time by creating some Docker images with the 'prepare' already executed in them.
We could recreate the Docker images on the push events to main branch when prepare script is modified, so the images would be always available with the latest changes.

**Comment by jspricke** [comment]
As discussed in person caching the internet is hard so let's not do that. Also it takes only a minute (and could be speed up if needed).
