### ISSUE TITLE
Build a package thats depends of a local cpp package

### ISSUE THREAD

**Issue by jginesclavero** [jspricke/ros-deb-builder-action#27]
Hi @jspricke,

I have a package that depends on a local cpp package ([CppLinuxSerial](https://github.com/gbmhunter/CppLinuxSerial)). CppLinuxSerial is not installable with apt, and I don't know where and how I should specify this dependency. 

I clarify that I am running the build scripts directly on a Ubuntu 22.04 machine and it works correctly with other packages.

I have tried to compile and install it with make and include it in the package.xml of my package, getting this error.

![image](https://github.com/jspricke/ros-deb-builder-action/assets/10533506/f9bbd281-9eed-4a91-a035-7e3908f75769)

I have tried to generate a .deb of cpplinuxinstall [following this guide](https://www.makeuseof.com/create-deb-packages-debian-ubuntu/) and include it in the apt_repo directory, without effect.

Any ideas?

Thank you so much!

**Comment by jspricke** [comment]
You need to add the key to rosdep, similar to here:

https://github.com/jspricke/ros-one-packages/blob/main/rosdep.yaml
https://github.com/jspricke/ros-one-packages/blob/main/.github/workflows/build.yaml#L15

**Comment by jginesclavero** [comment]
Oh nice! I was failing with the semantics and the correct tags, but it works!

Thank you so much again!
