### ISSUE TITLE
Pipeline Ubuntu 20.04 and Noetic

### ISSUE THREAD

**Issue by g-gemignani** [jspricke/ros-deb-builder-action#28]
Hi @jspricke,

Thank you so much for this contribution! In the past few weeks, I was trying to package this repo https://github.com/aiplan4eu/UP4ROS, and I was now thinking to use your action. However, when I added it to the UP4ROS workflow I got this error: 

> Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
> Err:1 http://deb.debian.org/debian bullseye InRelease
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 605C66F00D6C9793
> Reading package lists...
> W: GPG error: http://deb.debian.org/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 605C66F00D6C9793
> E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.

Link to build: https://github.com/aiplan4eu/UP4ROS/actions/runs/4875405225/jobs/8697550216 
Is this expected? Do I need to modify my workflow?
Thank you! :smile:

**Comment by jspricke** [comment]
The workflow needs 22.04 as the host VM here: https://github.com/aiplan4eu/UP4ROS/blob/devel/.github/workflows/debian.yaml#L13

**Comment by g-gemignani** [comment]
Yep, that was the deal. Now failing for other reasons. Thank you for the support!

**Comment by g-gemignani** [comment]
Never mind, here is the issue again:
https://github.com/aiplan4eu/UP4ROS/actions/runs/4978675377/jobs/8909281587

**Comment by jspricke** [comment]
>  E: The repository 'http://packages.ros.org/ros/ubuntu bullseye Release' does not have a Release file.

There is no noetic distribution for bullseye. Either use a supported noetic distribution (buster or focal) or switch to the `debian` `ROS_DISTRO` ;).

**Comment by g-gemignani** [comment]
Ah clear! I thought that DEB_DISTRO meant the debian distro, and since focal is based on bullseye, that is why I added it. Now everything got solved. Thank you!

**Comment by g-gemignani** [comment]
Oh ok, I thought bullseye since this is what my computer with Ubuntu 20.04 was saying:

> $ cat /etc/debian_version 
> bullseye/sid

Good to know. Thanks again for the help!

**Comment by jspricke** [comment]
sid is the codename for unstable and and that time bullseye was the next version
