### ISSUE TITLE
boolean values for the action configuration are not YAML compliant

### ISSUE THREAD

**Issue by esteve** [jspricke/ros-deb-builder-action#31]
`SQUASH_HISTORY` and `GIT_LFS` are boolean according to the documentation, but they are not parsed as such at all.

The YAML spec accepts many values for `true` / `false` (see https://yaml.org/type/bool.html), however `SQUASH_HISTORY` only accepts `true` (and none of the `false` variants). Moreover, if `GIT_LFS` is set to any value (including `false`), it's interpreted as true.

**Comment by jspricke** [comment]
correct.

**Comment by esteve** [comment]
@jspricke I saw you force pushed #29 without addressing https://github.com/jspricke/ros-deb-builder-action/pull/29#discussion_r1204004266, I really don't know why you did that. Contributing to this repository is definitely one of my least pleasant experiences in recent times. I don't undertand any of this hostility.

**Comment by jspricke** [comment]
I'm sorry if you feel hostility, I honestly feel the same from you. `SQUASH_HISTORY` indeed is a bit inconsistent and I consider that legacy. Directly passing yaml values to shell scripts is obviously a simplification but I think it is easy enough to not do wrong so I consider this a esoteric issue. My point for doing it like this is that the shell script philosophy is different to the yaml syntax but as this project is a shell script so that is how it should be done.

**Comment by esteve** [comment]
> I'm sorry if you feel hostility, I honestly feel the same from you.

Being positive, I think it's good that we both see that there's a conflictive situation here. It would be great to discuss what we can do to improve the communication between us and make our interactions more pleasant. Feel free to drop me an email at github.jochen@fernandez.cc and let me know your thoughts. 

> `SQUASH_HISTORY` indeed is a bit inconsistent and I consider that legacy. Directly passing yaml values to shell scripts is obviously a simplification but I think it is easy enough to not do wrong so I consider this a esoteric issue.

I see, thanks for the explanation. I still think there are ways to mitigate cases like this, that while not perfect, I admit, are still good enough. I don't know if this a personal project of yours or if it's maintained by PickNick, so it's your call to close issues of course. But in my opinion it would be good to keep this issue open as it would be beneficial for users to know that the known limitations of the project have been accounted for, even if they are not being worked on currently.

> My point for doing it like this is that the shell script philosophy is different to the yaml syntax but as this project is a shell script so that is how it should be done.

Given the limitations of shell scripts, would you be open to the idea of incorporating (or rewriting some parts in) other high level languages? For example, we'd like to contribute some features that, although doable in shell scripts, are far more complex to implement than in other languages (e.g. parallelize package builds while maintaining the dependency graph).

**Comment by jspricke** [comment]
> I see, thanks for the explanation. I still think there are ways to mitigate cases like this, that while not perfect, I admit, are still good enough.

I agree that it could be improved, I would do that by having a small script that translates between both concepts.

> Given the limitations of shell scripts, would you be open to the idea of incorporating (or rewriting some parts in) other high level languages?

I don't see a need for that.

> For example, we'd like to contribute some features that, although doable in shell scripts, are far more complex to implement than in other languages (e.g. parallelize package builds while maintaining the dependency graph).

I'm doing that one right now for an other company and we will eventually publish it but I'm unsure about adding it to this action as the Github VM is rather resource limited. Also we probably want to incorporate https://github.com/v4hn/ros-o-builder at some point. Let's have a video call about what to do here.
