### ISSUE TITLE
Unable to locate package vcstool

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#33]
At some point, the pipeline runs:
```sh
sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends sbuild mmdebstrap distro-info debian-archive-keyring ccache uidmap vcstool python3-rosdep2 catkin python3-bloom curl apt-cacher-ng git-lfs
```
which fails with:
```
E: Unable to locate package vcstool
```
because the package `vcstool` does not exist. The correct package name is `python3-vcstool`.

The same goes for package `colcon` which is in
```
sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends sbuild mmdebstrap distro-info debian-archive-keyring ccache uidmap vcstool python3-rosdep2 colcon python3-colcon-package-information python3-colcon-ros python3-bloom curl apt-cacher-ng git-lfs
```
and should also be replaced by `python3-colcon-common-extensions`.

**Comment by jspricke** [comment]
Can you post a link to the log? `vcstool` is part of `ppa:v-launchpad-jochen-sprickerhof-de/sbuild` which should be installed.

**Comment by jspricke** [comment]
Also it is listed as an alternative already: https://github.com/jspricke/ros-deb-builder-action/blob/main/prepare#L37

**Comment by christian-rauch** [comment]
> Can you post a link to the log? `vcstool` is part of `ppa:v-launchpad-jochen-sprickerhof-de/sbuild` which should be installed.

I cannot share the log publicly. I don't see anything related to "launchpad" or "ppa" in the debug logs. My best guess is that this is related to proxy settings. I later get `apt-get update -oAPT::Status-Fd=<$fd> -oDpkg::Use-Pty=false failed` during `mmdebstrap` but `apt install` works for the packages from the regular repo at  http://archive.ubuntu.com.

**Comment by jspricke** [comment]
Which OS do you run on?
Currently this Action is only supported on Ubuntu 22.04/jammy, as this is supported by Github Actions, but should also work on Ubuntu 23.04/lunar and up as well as Debian bookworm and up.

**Comment by christian-rauch** [comment]
> Currently this Action is only supported on Ubuntu 22.04/jammy

That's an important piece of information. I switched the Action to use 22.04/humble container images and some of these problems disappeared.

I am still getting a couple of errors and warnings:
- `W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

-
  ```
  Some packages could not be installed. This may mean that you have
  requested an impossible situation or if you are using the unstable
  distribution that some required packages have not yet been created
  or been moved out of Incoming.
  The following information may help to resolve the situation:
  
  The following packages have unmet dependencies:
   python3-catkin-pkg : Conflicts: catkin but 0.8.10-7 is to be installed
   python3-catkin-pkg-modules : Conflicts: catkin but 0.8.10-7 is to be installed
   python3-rosdep : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
   python3-rosdep-modules : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
  E: Unable to correct problems, you have held broken packages.
  ```

- `E: Unable to locate package colcon`

**Comment by jspricke** [comment]
> I am still getting a couple of errors and warnings:
> 
> * `W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`
> * ```

That seems unrelated to this Action.

>   Some packages could not be installed. This may mean that you have
>   requested an impossible situation or if you are using the unstable
>   distribution that some required packages have not yet been created
>   or been moved out of Incoming.
>   The following information may help to resolve the situation:
>   
>   The following packages have unmet dependencies:
>    python3-catkin-pkg : Conflicts: catkin but 0.8.10-7 is to be installed
>    python3-catkin-pkg-modules : Conflicts: catkin but 0.8.10-7 is to be installed
>    python3-rosdep : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
>    python3-rosdep-modules : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
>   E: Unable to correct problems, you have held broken packages.
>   ```
> * `E: Unable to locate package colcon`

These are probably due to trying different package sets first and can be ignored: https://github.com/jspricke/ros-deb-builder-action/blob/main/prepare#L35

**Comment by jspricke** [comment]
> > Currently this Action is only supported on Ubuntu 22.04/jammy
> 
> That's an important piece of information. I switched the Action to use 22.04/humble container images and some of these problems disappeared.

This is documented: https://github.com/jspricke/ros-deb-builder-action/tree/main#run-manually

**Comment by jspricke** [comment]
> This only talks about running locally and it does not say that older versions will not work. In my eyes, this could be more explicit.

Patches welcome :).
