### ISSUE TITLE
Cannot install rosdep2 and bloom

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#34]
I am trying to run this locally on Ubuntu 22.04 as described in https://github.com/jspricke/ros-deb-builder-action#run-manually.

I am somehow in a state, where `sudo apt install python3-rosdep2` will remove `python3-bloom`
```
The following packages will be REMOVED
  python3-bloom python3-rosdep python3-rosdep-modules
The following NEW packages will be installed
  python3-rosdep2
```
resulting in
```
ros-deb-builder-action/build: 106: bloom-generate: not found
```
when I run `./build -r humble -d jammy` locally on Ubuntu 22.04.

Trying to install `python3-bloom` will remove `python3-rosdep2`.

Isn't it possible to run this with package `python3-rosdep` instead? I.e. `sudo apt install python3-bloom python3-rosdep` would work but `sudo apt install python3-bloom python3-rosdep2` results in:
```
The following packages have unmet dependencies.
 python3-rosdep : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
 python3-rosdep-modules : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I noticed that `./prepare -d jammy` already shows an error:
```
The following packages have unmet dependencies.
 python3-catkin-pkg : Conflicts: catkin but 0.8.10-7 is to be installed
 python3-catkin-pkg-modules : Conflicts: catkin but 0.8.10-7 is to be installed
 python3-rosdep : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
 python3-rosdep-modules : Conflicts: python3-rosdep2 but 0.21.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I am also seeing:
```
+ sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends sbuild mmdebstrap distro-info debian-archive-keyring ccache uidmap vcstool python3-rosdep2 colcon python3-colcon-package-information python3-colcon-ros python3-bloom curl git-lfs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package colcon
```
There is no package `colcon`. One has to install the `python3-colcon-*` packages instead.

**Comment by jspricke** [comment]
I guess you have the OSRF packages installed. This should work for you:
https://github.com/jspricke/ros-deb-builder-action/blob/main/prepare#L37

**Comment by christian-rauch** [comment]
> I guess you have the OSRF packages installed.

Yes, I already have ROS 2 humble installed.

> This should work for you: https://github.com/jspricke/ros-deb-builder-action/blob/main/prepare#L37

I can run this command but it does not resolve the dependency issue. `sudo apt install python3-bloom python3-rosdep2` still reports the same issue.

Given the dependencies and conflicts
```
$ apt-cache depends python3-bloom 
python3-bloom
  Depends: <python3:any>
    python3
  Depends: python3-yaml
  Depends: python3-empy
  Depends: python3-rosdep
  Depends: python3-rosdistro
  Depends: python3-vcstools
  Depends: python3-setuptools
  Depends: python3-catkin-pkg
  Conflicts: <python-bloom>
$ apt-cache depends python3-rosdep
python3-rosdep
  Depends: <python3:any>
    python3
  Depends: python3-rosdep-modules
  Conflicts: <python-rosdep>
  Conflicts: <python-rosdep2>
  Conflicts: python3-rosdep2
$ apt-cache depends python3-rosdep2
python3-rosdep2
  Depends: python3-catkin-pkg
  Depends: python3-rosdistro
  Depends: python3-rospkg
  Depends: python3-yaml
  Depends: <python3:any>
    python3
  Depends: ca-certificates
```
I don't see how this can be resolved (`python3-bloom` requires `python3-rosdep` and `python3-rosdep` conflicts with `python3-rosdep2`).

**Comment by jspricke** [comment]
The `python3-bloom` in the OSRF repo depends on `python3-rosdep? not `python3-rosdep2`.

**Comment by jspricke** [comment]
it is not the od package, just a different name.

**Comment by christian-rauch** [comment]
> So does it work for you now so we can close this?

No. I still have these dependency conflicts.

The suggested command (https://github.com/jspricke/ros-deb-builder-action/blob/a773469b7aa118a1f183a3369d4e3fdbf348f588/prepare#L37) runs through, but because of the rosdep <-> rosdep2 conflict, I cannot install `python3-bloom` and `python3-rosdep2` simultaneously.

**Comment by jspricke** [comment]
Why would you want to install `python3-rosdep2`? It is not needed

**Comment by christian-rauch** [comment]
> Why would you want to install `python3-rosdep2`? It is not needed

Without it, I get the error:
```
ERROR: Not all sources were able to be updated.
[[[
ERROR: unable to process source [file:///usr/share/python3-rosdep2/debian.yaml]:
	<urlopen error [Errno 2] No such file or directory: '/usr/share/python3-rosdep2/debian.yaml'> (file:///usr/share/python3-rosdep2/debian.yaml)
]]]
```

**Comment by christian-rauch** [comment]
As a workaround, you can force a downgrade via `sudo apt install python3-bloom=0.10.7-2 python3-rosdep2`. Then it seems to work. But this is not robust and will probably break again after an update.

It would be great if the scripts could work with either of the rosdep packages.

**Comment by jspricke** [comment]
Does `apt purge python3-rosdep2` help?

**Comment by christian-rauch** [comment]
> Does `apt purge python3-rosdep2` help?

No. It does not help with the dependency resolution afterwards as, at least in my case, I always have to reinstall it afterwards to provide `/usr/share/python3-rosdep2/debian.yaml`.

The only thing that helped was forcing a downgrade of `python3-bloom` to the version provided by the Ubuntu repos.

**Comment by jspricke** [comment]
That sounds odd. After `apt purge python3-rosdep2` there should no longer be a `/etc/ros/rosdep/sources.list.d/10-debian.list` and thus nothing including `file:///usr/share/python3-rosdep2/debian.yaml`. What is the content of your `/etc/ros/rosdep/sources.list.d/` after the purge?

**Comment by christian-rauch** [comment]
> That sounds odd. After `apt purge python3-rosdep2` there should no longer be a `/etc/ros/rosdep/sources.list.d/10-debian.list` and thus nothing including `file:///usr/share/python3-rosdep2/debian.yaml`. What is the content of your `/etc/ros/rosdep/sources.list.d/` after the purge?

Sure, after the purge these files are gone. But the script, somehow, requires `/usr/share/python3-rosdep2/debian.yaml` so I have to reinstall it anyway. Sorry, if this was not clear from my previous post.

**Comment by jspricke** [comment]
Why do you think it depends on that file? Can you post a command invocation and the error?

**Comment by christian-rauch** [comment]
It turns out I have to manually run `rosdep update` after removing rosdep2 and installing rosdep. I guess it would be more robust if the `build` script would run this in any case to avoid this issue on local setups.

**Comment by jspricke** [comment]
`rosdep update` is run here: https://github.com/jspricke/ros-deb-builder-action/blob/main/build#L82

**Comment by christian-rauch** [comment]
Sorry. Then I am not really sure what happened and why the index was out of date.
