### ISSUE TITLE
no network connection during build

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#38]
I am trying to build a package that downloads an archive (via `ExternalProject_Add` in the `CMakeLists.txt`) from a public URL.

This fails with something like:
```
-- Downloading...
   dst='/<<BUILDDIR>>package/obj-x86_64-linux-gnu/torch_archive/src/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
-- Retrying...
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip'
CMake Error at torch_archive-stamp/download-torch_archive.cmake:170 (message):
  Each download failed!

    error: downloading 'https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcu118.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: download.pytorch.org
```

See https://github.com/christian-rauch/mmf-ros-deb-builder for the project with CI and `sources.repos`.

**Comment by jspricke** [comment]
sbuild, in unshare mode, does not allow network access during the build, as per Debian policy. The Debian way would be to either package those downloads as separate packages or add them to the package, for example with git-lfs. While I really love this policy, I completely agree that it does not apply outside of Debian (and Ubuntu) and I am still debating with myself to propose a switch to make it optional (in sbuild or even in the package metadata).
As a workaround you could fork this repo and do something like:
```
sed -i "s/DISABLE_NETWORK.*/DISABLE_NETWORK => 0,/" /usr/share/perl5/Sbuild/Build.pm
```

**Comment by christian-rauch** [comment]
I wasn't aware of this restriction. Many projects in the wild download build dependencies in the build script, e.g. via `ExternalProject_Add`. All these projects would need some kind of workaround for packaging.

I am trying to find out more about this and was looking at https://www.debian.org/doc/debian-policy/ but cannot find anything related to `sbuild` or `unshare`. Could you point me to where the restriction to network during build is described?

Do you know how the ROS 2 buildfarm (https://build.ros2.org) handles this? In any case, I think this GitHub action should replicate the official build farm behaviour as closely as possible. If the buildfarm also prevents network access during build time, then this would be ok but should be documented here.

**Comment by jspricke** [comment]
> I am trying to find out more about this and was looking at https://www.debian.org/doc/debian-policy/ but cannot find anything related to `sbuild` or `unshare`. Could you point me to where the restriction to network during build is described?

Debian policy 4.9:
> For packages in the main archive, required targets must not attempt network access, except, via the loopback interface, to services on the build host that have been started by the build.

> Do you know how the ROS 2 buildfarm (https://build.ros2.org) handles this? In any case, I think this GitHub action should replicate the official build farm behaviour as closely as possible. If the buildfarm also prevents network access during build time, then this would be ok but should be documented here.

Afaik the ROS buildfarm allows network access. I am still unsure here, in principal I think restricting network access is really good and I would like to promote it more outside of Debian. On the other hand I am aware that this is currently not the norm. As written, I will think about providing a patch to sbuild which would allow to make it configurable in this Action.

**Comment by christian-rauch** [comment]
The ROS buildfarm supports multiple package formats, so I guess they will follow the "union" of packaging rules where other Distributions and package formats may allow network access during the build.

As a real-world example, the `tinyxml_vendor` package [downloads its source at build time](https://github.com/ros2/tinyxml_vendor/blob/11eb1488c2b0b632ed548f8e3a22d4432a1bc0c4/CMakeLists.txt#L24-L40).
Without network access, it would not be possible to build these official ROS packages with this GitHub action. Would it be possible to override the behaviour using the `~/.sbuildrc`?

**Comment by jspricke** [comment]
> As a real-world example, the `tinyxml_vendor` package [downloads its source at build time](https://github.com/ros2/tinyxml_vendor/blob/11eb1488c2b0b632ed548f8e3a22d4432a1bc0c4/CMakeLists.txt#L24-L40).

But only if the library is not found on the system (line 16).
Btw. this is a good example why downloading during build is a bad idea. You can't link multiple versions of a library into the same executable¹ so in case you want to compile a binary that also links against a system library that happen to link against a system tinyxml there is a risk of random segfaults. This is one of the reasons why Debian policy forbids code copies (4.13).

> Would it be possible to override the behaviour using the `~/.sbuildrc`?

Currently that is not implemented.

¹: Technically you can and also add namespaces to work around breakage but I would not recommend that.

**Comment by jspricke** [comment]
maybe we could provides hooks into the action, something like `PRE_BUILD_HOOK=<cmds` where the sed can be executed for now. What do you think?

**Comment by jspricke** [comment]
This is now configurable in sbuild: https://salsa.debian.org/debian/sbuild/-/merge_requests/61 (still needs a new sbuild release and then either upload to the PPA or a new Ubuntu release, whatever comes next..)

**Comment by christian-rauch** [comment]
Thanks a lot!

**Comment by jspricke** [comment]
The new feature is now in Debian testing and will be in Ubuntu 24.04. I will keep this open until it is available as a Github image but don't intent to do more here.

**Comment by Timple** [comment]
I think the main issue here is that it is solved in ubuntu 24.04. But `python3-rosdep2`, `catkin` and `python3-bloom` are not available anymore in ubuntu 24.04: 
https://www.ubuntuupdates.org/package/core/noble/universe/base/python3-rosdep2. 

Thus this action cannot be used as-is in ubuntu 24.04.

**Comment by christian-rauch** [comment]
> I think the main issue here is that it is solved in ubuntu 24.04. But `python3-rosdep2`, `catkin` and `python3-bloom` are not available anymore in ubuntu 24.04: https://www.ubuntuupdates.org/package/core/noble/universe/base/python3-rosdep2.

They are available in the ROS apt repo or via pip. Some, such as [`colcon-core`](https://packages.ubuntu.com/noble/python3-colcon-core), are available in Ubuntu 24.04. But not sure one would go that path if official packages are available via an apt repo or pip.

> Thus this action cannot be used as-is in ubuntu 24.04.

Did you actually try?

**Comment by Timple** [comment]
> Did you actually try?

I did: https://github.com/nobleo/ros_debian_packages/actions/runs/10661923303/job/29548220439

> They are available in the ROS apt repo or via pip.

@jspricke made it clear that ROS repo would not be used: https://github.com/jspricke/ros-deb-builder-action/pull/51#issuecomment-2119150449

**Comment by christian-rauch** [comment]
> > Did you actually try?
> 
> I did: https://github.com/nobleo/ros_debian_packages/actions/runs/10661923303/job/29548220439

That's using quite an old branch of mine. Did you try to use the newest upstream with the "network" patch?

> > They are available in the ROS apt repo or via pip.
> 
> @jspricke made it clear that ROS repo would not be used: [#51 (comment)](https://github.com/jspricke/ros-deb-builder-action/pull/51#issuecomment-2119150449)

```yaml
    runs-on: ubuntu-24.04
    steps:
      - uses: [...]/ros-deb-builder-action
        with:
          ROS_DISTRO: iron
          DEB_DISTRO: jammy
```

Note that there is a difference between the runner (`runs-on`) and your target distribution given in `DEB_DISTRO`. You run the action on `24.04` but are still targeting `jammy` / `22.04`.

**Comment by Timple** [comment]
> That's using quite an old branch of mine. 

Actually I should try this repository as it's solved upstream in 24.04 right? I actually did try that here: https://github.com/nobleo/ros_debian_packages/commit/8dae0f48e55d0bcb7981b9ad7a375a7c98fc56da
Without success. I can try again.

> Note that there is a difference between the runner (runs-on) and your target distribution given in DEB_DISTRO. 

I know. I need the runner to be 24.04 to have the latest `sbuild`. I'm targetting multiple ROS distros.

**Comment by jspricke** [comment]
@Timple can you try the latest master?

**Comment by Timple** [comment]
Installing colcon works! So I'm going to assume the rest works as well :slightly_smiling_face: 

Thank you!

**Comment by christian-rauch** [comment]
Since https://salsa.debian.org/debian/sbuild/-/merge_requests/61 has been merged, it should be possible to build with network access.

The documentation mentions `SBUILD_CONF="$enable_network = 1;"`, that is `SBUILD_CONF: "$enable_network = 1;"` in the CI yaml configuration. However, in the CI I get the error:
```
E: /github/home/.sbuildrc: Errors found in configuration file:
Global symbol "$enable_network" requires explicit package name (did you forget to declare "my $enable_network"?) at (eval 28) line 7.
```

Ideally, this should work for all packages that are specified in the `.repos` file.

@jspricke How is this new `enable-network` option supposed to be used in the CI? Can you update the documentation with an example?

**Comment by jspricke** [comment]
@christian-rauch which sbuild version did you use?

**Comment by christian-rauch** [comment]
> @christian-rauch which sbuild version did you use?

I was about to say "The default for Ubuntu 22.04 and 24.04." but then I saw that all my jobs (`humble` and `jazzy`) use the `ubuntu:22.04` container. Switching to `ubuntu:24.04` fixes the issue. Sorry for the noise.

**Comment by qiayuanl** [comment]
> sbuild, in unshare mode, does not allow network access during the build, as per Debian policy. The Debian way would be to either package those downloads as separate packages or add them to the package, for example with git-lfs. While I really love this policy, I completely agree that it does not apply outside of Debian (and Ubuntu) and I am still debating with myself to propose a switch to make it optional (in sbuild or even in the package metadata). As a workaround you could fork this repo and do something like:
> 
> ```
> sed -i "s/DISABLE_NETWORK.*/DISABLE_NETWORK => 0,/" /usr/share/perl5/Sbuild/Build.pm
> ```

Where should I put it? Now I do something like [this](https://github.com/qiayuanl/ros-deb-builder-action/blob/main/prepare#L86), but it doesn't work.

**Comment by jspricke** [comment]
@qiayuanl what's your use case? Can you switch to Ubuntu 24.04?

**Comment by qiayuanl** [comment]
> [@qiayuanl](https://github.com/qiayuanl) what's your use case? Can you switch to Ubuntu 24.04?

No. As we mentioned in #57, there is a problem with ubuntu 24.04 in arm64 environment. So I want to try back to 22.04

**Comment by jspricke** [comment]
Totally forgot, sorry. Do you have a log where it fails?

**Comment by qiayuanl** [comment]
[Here](https://github.com/qiayuanl/legged_buildfarm/actions/runs/12918606536/job/36027468744#step:6:22690)

```
  -- Using src='https://github.com/google-deepmind/mujoco/releases/download/3.2.6/mujoco-3.2.6-linux-x86_64.tar.gz'
  CMake Error at _deps/mujocodownload-subbuild/mujocodownload-populate-prefix/src/mujocodownload-populate-stamp/download-mujocodownload-populate.cmake:170 (message):
    Each download failed!
```

Note that I modified the action and tested it with amd64 only because it runs much faster than arm64. Everything works before [this commit](https://github.com/qiayuanl/legged_buildfarm/commit/248e542ed4801f82b1e711d1e4787a0827fcdfa1).

**Comment by jspricke** [comment]
you want the `sed` before the `exit? in line 83.

**Comment by qiayuanl** [comment]
It works! Thanks.
