### ISSUE TITLE
multiverse and restricted repos

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#40]
It is not possible to resolve rosdep keys that point to packages in the `multiverse` and `restricted` Ubuntu repositories. `mmdebstrap` is currently only configured with `--components=main,universe` which prevents building a subset of ROS packages. Using all repos (`--components=main,universe,multiverse,restricted`) would allow to resolved those rosdep keys too.

**Comment by jspricke** [comment]
You can add them via `EXTRA_REPOSITORIES` in https://github.com/jspricke/ros-deb-builder-action#sbuild_conf.
I don't think we should add them by default as they don't contain free software.

**Comment by christian-rauch** [comment]
Thanks. Adding `SBUILD_CONF: "$extra_repositories = [ 'deb [signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://archive.ubuntu.com/ubuntu jammy multiverse restricted' ];"` eventually worked for me.

However, I think this is quite error-prone and at least an option to extend `--components` would be more robust.
