### ISSUE TITLE
Debian package version does not match package.xml

### ISSUE THREAD

**Issue by christian-rauch** [jspricke/ros-deb-builder-action#45]
In https://github.com/jspricke/ros-deb-builder-action/blob/2e4870fe77a540ccb91931ede1c54255805c9f54/build#L120 the version in the `changelog` is replaced. What is the motivation for this?

For me, this changes the Debian package version to something that is not related to the package.xml anymore. E.g. I start of with a version `0.2.0-0jammy` that is replaced with `0.2.0-111-g8ed59e73-2024.04.27.22.49` which eventually translated to a Debian package with version `0-2024.04.27.12.46`.

This is different from the Debian packages generated by the ROS build farm and makes it very hard to relate a Debian package to the version in the package.xml. Concretely, while the build farm generates a package `ros-humble-libcamera_0.2.0-1jammy_arm64.deb`, for which `dpkg -I` will show `Version: 0.2.0-1jammy`, this action generates a package `ros-humble-libcamera_0-2024.04.27.09.47_arm64.deb` with `Version: 0-2024.04.27.09.47`.

Is this intended? If so, what is the advantage of replacing the original version like this?

**Comment by jspricke** [comment]
The action is meant as a CI system so new commits should have higher version numbers. You can get similar versions to the ROS build farm by pushing a tag to your repo.

**Comment by christian-rauch** [comment]
You are right. The original repo contains tags, but my fork that I was actually using in the action did not contain the upstream tags. Therefore, `git describe --tag` failed and it was actually using version `0` from `echo 0`.

**Comment by qiayuanl** [comment]
I found that it doesn't work with the checkout repo. 

For example: I have a private repo `qiayuanl/legged_control2` in
https://github.com/qiayuanl/legged_buildfarm/blob/master/.github/workflows/build_humble_amd64.yml

I ran `bloom-generate rosdebian` locally, got below in the changelog
```
ros-humble-legged-model (1.1.0-0jammy) jammy; urgency=high
```
which is correct.

Then I run 
 `sed -i "1 s@([^)]*)@($( (git describe --tag  --match "*[0-9]*" 2>/dev/null || echo 0) | sed -e 's@^[^0-9]*@@' -e 's@_@~@g')-$(date +%Y.%m.%d.%H.%M))@" debian/changelog`
got 
```
ros-humble-legged-model (1.1.0-2025.03.26.18.26) jammy; urgency=high
```
which is also what I want.


**But** when I run as [github action](https://github.com/qiayuanl/legged_buildfarm/tree/jammy-humble-amd64), I got
```
ros-humble-legged-model_0-2025.03.27.01.05
```

**Comment by jspricke** [comment]
@qiayuanl are you sure the tag is pushed to GIthub?

**Comment by qiayuanl** [comment]
Yes.
![Image](https://github.com/user-attachments/assets/aa8fec08-910b-406a-a5d0-088172fc3775)

**Comment by jspricke** [comment]
Then I don't know and as the repo is private I can't investigate.

**Comment by qiayuanl** [comment]
Sorry, let me invite you to this repo.
It is very weird.

**Comment by jspricke** [comment]
not interested in debugging closed source, sorry.

**Comment by qiayuanl** [comment]
> not interested in debugging closed source, sorry.

It doesn't matter closed source or not, right? I can have a dummy open-source package that reproduces the same problem.

The key point is when I turn on `SKIP_CHECKOUT` and construct the repo/workspace by myself, the code mentioned in this issue doesn't work.

**Comment by qiayuanl** [comment]
Nevermind. I think is because I am using incorrect checkout action parameters. Sorry for the message.
