### ISSUE TITLE
Package without catkin wrapper

### ISSUE THREAD

**Issue by qiayuanl** [jspricke/ros-deb-builder-action#52]
Hi, this action is very helpful, thanks for the contribution.

I am trying to build the [robot_interface](https://github.com/open-dynamic-robot-initiative/robot_interfaces). They use colcon to build and use the treep for managing the package (basically clone every dependency repo into a workspace).

I add all dependencies manually like [ros2.repos](https://github.com/qiayuanl/hrg_buildfarm/blob/master/ros2.repos). And try to use your actions.

However, the [actions fail](https://github.com/qiayuanl/hrg_buildfarm/actions/runs/9576068591/job/26401952684) because most of the dependencies are not catkin packages, in fact, only robot_interface has a package.xml. 

Will it work If I directly add these packages into rodep? Or do I need to warp every package like [pybind11](https://github.com/pybind/pybind11)->[pybind11_catkin](https://github.com/wxmerkt/pybind11_catkin)?

**Comment by jspricke** [comment]
This action uses bloom that relies on a `package.xml` to generate a Debian source package. You need to add one for every dependency (either directly or in a wrapper package). Closing as not an issue.
