### ISSUE TITLE
Confusion about the name of the branch used to push the built packages

### ISSUE THREAD

**Issue by JafarAbdi** [jspricke/ros-deb-builder-action#54]
These two commits https://github.com/jspricke/ros-deb-builder-action/commit/27389f5b927231e914028dcdbfead6f6805de462 and https://github.com/jspricke/ros-deb-builder-action/commit/57549104d7e747d2675723db5df68382626c84f1 added the architecture to the branch name, if we explicitly set PACKAGES_BRANCH the name will be `$PACKAGES_BRANCH-$DEB_ARCH`

Should I open a PR to update the description of PACKAGES_BRANCH to mention DEB_ARCH as well or just update the default value of PACKAGES_BRANCH to be `$DEB_DISTRO-$ROS_DISTRO-$DEB_ARCH`?

**Comment by jspricke** [comment]
Hi Jafar, thanks for pointing out! I think fixing the default makes more sense, a PR would be great.
