### ISSUE TITLE
Unable to build ament-cmake-core

### ISSUE THREAD

**Issue by ArendJan** [jspricke/ros-deb-builder-action#56]
I'm trying to cross-compile all of ROS2 for armhf, but in a test for amd64 it is already failing.

build log: https://github.com/ArendJan/mirte-ros-packages/actions/runs/11435799080/job/31811900490#step:4:1264
(line 1299)

 ```
-- Found Python3: /usr/bin/python3 (found version "3.10.12") found components: Interpreter 
  -- ament_cmake_core 1.3.10
  Traceback (most recent call last):
    File "/<<BUILDDIR>>package/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
      from ament_package.templates import get_environment_hook_template_path
  ModuleNotFoundError: No module named 'ament_package'
  CMake Error at ament_cmake_package_templates-extras.cmake:41 (message):
    execute_process(/usr/bin/python3
    /<<BUILDDIR>>package/cmake/package_templates/templates_2_cmake.py
    /<<BUILDDIR>>package/obj-x86_64-linux-gnu/ament_cmake_package_templates/templates.cmake)
    returned error code 1
  Call Stack (most recent call first):
    CMakeLists.txt:19 (include)
```
The workflow for this simplified example:
https://github.com/ArendJan/mirte-ros-packages/blob/test_autobuild/.github/workflows/buildROSErr.yaml using a simple sources file:
https://github.com/ArendJan/mirte-ros-packages/blob/test_autobuild/ros2_err_sources.repos (first one already fails)

The log shows that `ros-humble-ament-package` gets installed.

I was able to build ROS2 humble before, without the generated debs, so it should be possible.

Do you know how to fix this?

**Comment by jspricke** [comment]
`ament_package` is from `ros-humble-ament-package` and thus located in `/opt/ros/humble/lib/python3.10/site-packages/ament_package`. For that we would need to set a `$PYTHONPATH` so it can be found. Usually this is set by `/opt/ros/humble/setup.sh` which is in `ros-humble-ros-workspace` and sourced by the `debian/rules` file generated by `bloom`, if found. So for this case it would be enough to add the missing build dependency to this package. But this will not help you for the bootstrap case as it introduces a (build) dependency cycle between both packages. I think `ament_cmake_core` needs some logic to search for a usable `ament_package` without sourcing a `setup.sh`.

Closing as not related to the action.
